name: starsync_go
description: A social/companion app for DAW integration, with Firebase Auth.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.9.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/starsync-logo.jpg
